### ISSUE TITLE
zHorse Claim Problem

### ISSUE THREAD

**Issue by EK6511** [Xibalba/ZHorse#101]
# Please be aware that ZHorse developement and maintenance is put on hold for the moment.
# However, this issue page remains open for questions and quick support.
# If your ticket requires modifications of the code, you will have to wait until either me or another developer resumes the project.

### What are you trying to do ?

i want to own a horse with the command /zh claim [name].

### What is the expected behavior ?

Own a Horse.

### What is the actual behavior ?

does not work

### How to reproduce the bug ?

1. Step 1
2. Step 2
3. ...

### Console output 

https://pastebin.com/night_mode

## Environment specifications

- Operating system : Windows 10

- Java version : 8

- Server version : 1.13.2

- ZHorse version : 1.7.1

- Database : SQLite

**Comment by Zedd7** [comment]
Link invalid.

**Comment by EK6511** [comment]
https://pastebin.com/PdSh80mF

Excuse me. Here's the right link.

**Comment by Zedd7** [comment]
It says that your permission plugin does not handle (primary) permission groups. I can't really do anything about it as ZHorse simply submitted a request to Vault (which handles permissions and economy stuff) and Vault replied that SuperPerms has no support for groups : "SuperPerms no group permissions" (line 24).

I checked ZHorse's code to see if it was possible to trick Vault by using ZHorse's virtual groups but, as ZHorse was coded with the assumption that permission plugins were able to handle groups, this is not possible.

So, you could either try to move to a different permission plugin (such as PermissionsBukkit, which is basic but does the job), forget about ZHorse, or find a developer able to work on [ZHorse's code](https://github.com/Zedd7/ZHorse/blob/master/src/main/java/com/github/zedd7/zhorse/managers/ConfigManager.java#L306) to handle the case of permission plugins not managing groups.
