### ISSUE TITLE
Other pets?

### ISSUE THREAD

**Issue by llaya** [Xibalba/ZHorse#102]
Is there a possibility you'd consider adding other pets like cats, dogs and parrots or even donkey's and llama's? It'd be lovely if players on servers could safely store them in virtual stables or even sell them to others.

**Comment by Zedd7** [comment]
Hi. Development of ZHorse is discontinued, therefore I cannot extend the plugin to other animals. However, donkeys and llamas are handled as horses by the game and supported by ZHorse, so you can claim them ;)
