### ISSUE TITLE
Horse duplication bug

### ISSUE THREAD

**Issue by taberruu** [Xibalba/ZHorse#11]
This bug appears quite often.

A player teleports his horse to himself & the horse appears beside him.
But the horse in the original place does not disappear!

(Latest Spigot 1.10 release & ZHorse 1.6.1)

Do you need further information/configs?

**Comment by Zedd7** [comment]
For this I will need you to update to Minecraft 1.11 and ZHorse 1.6.2 as I am unable to replicate this on any server.
