### ISSUE TITLE
MySql or Zhorse

### ISSUE THREAD

**Issue by muddup** [Xibalba/ZHorse#114]
### What are you trying to do ?

Upon login to server this is what i get in console

### What is the expected behavior ?

no error in console

### What is the actual behavior ?

should not receive this error.

### How to reproduce the bug ?

1. login
2. then it happens when logged in the error
3. ...

### Console output 

https://pastebin.com/nvKiY9fH

## Environment specifications

- Operating system : Windows 2016 Server

- Java version : 8 - latest version

- Server version : [16:52:27 INFO]: This server is running Paper version git-Paper-585 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:52:27 INFO]: Previous version: git-Paper-584 (MC: 1.13.2)

- ZHorse version : ZHorse 1.8.0

- Database : MySQL 8.0

**Comment by Zedd7** [comment]
I should be able to take a look at it this weekend. However I can't promise a quick fix if it requires lots of modifications to the code as I'm overbooked for the moment..

**Comment by Zedd7** [comment]
I checked your error logs and tried to reproduce your issue with different scenarios but did not encounter any problem as it seems to be exclusively related to MySQL.
What is likely happening is that the connection to your MySQL instance is lost and cannot me recovered. I don't know why it is happening (maybe you could double check your configuration, hosting solution, or whatever is relevant in this case) but it concerns me that the error mentions a connection loss of over **18 hours** ! Somethings is going terribly wrong here.

On ZHorse's side, I'm already testing the connection to the database before each query, attempting to reconnect if necessary, and have specified the relevant flags to the connection URL so I don't think that I could do anything more.

If your issue persists, I recommend that you switch to SQLite which shouldn't slow ZHorse thanks to the additions of version 1.8.0.

Sorry that I couldn't help much more, please keep me informed about this ;)

**Comment by muddup** [comment]
Hey thanks for checking this out.
Not sure why it is happening, as the other plugins don't seem to have 
this issue.
I have changed host provider, and they are allot faster than the 
previous one. I'll do some testing to see why the delay and let you know 
what I find.

Thanks,
Frank

------ Original Message ------
