### ISSUE TITLE
Trouble Claiming Horse

### ISSUE THREAD

**Issue by boxer2354** [Xibalba/ZHorse#115]
### What are you trying to do ?

Trying to use /zh claim

### What is the expected behavior ?

The horse I am sitting on should be claimed (I have already tamed it)

### What is the actual behavior ?

The chat stays blank and nothing happens. I saw someone else in the forums had a similar problem but I think I have a different but probably similar issue.

### How to reproduce the bug ?

1. I do /zh Claim (I have tried both putting a name after "claim" and not putting a name)
2. Nothing appears in the chat (no error message) and when i try do do other commands such as /zh protect it tells me that I must claim the horse first

### Console output 

https://mclo.gs/3H2O5Cs hopefully this link works

## Environment specifications

- Operating system : Windows

- Java version :

- Server version : 1.12.2

- ZHorse version : 1.7.0

- Database :

**Comment by Zedd7** [comment]
A similar issue was indeed submitted and the 'fix' given here : #112 
This will be fixed as of version 2.0.0 (#104) but it could take quite some time so I suggest that you either : 
* Switch to a permission plugin supporting permission groups. One of the simplest is PermissionsBukkit (still working to this day).
* Or use StylisMC's fix which consists on relying on surrogate groups. Simply put, set a permission for each ZHorse's group and assign it to the players of your choice. Normally (this feature as been tested but is somewhat experimental), ZHorse will simulate a permission group taking the name of the ZHorse group corresponding to the current permission.

See here for a example of such a ZHorse group : https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks#unexpected-limit-reached-message

**Comment by boxer2354** [comment]
I'm sorry but I am still a little confused, I'm not sure what plugin I have that is causing the issue of permissions. The only people that play on this server are myself and my little sister so I don't even have a need for permission groups. I had EssentialsX but I deleted that (although I will probably reinstall it if that isn't the issue)
Any ideas? Sorry for the trouble but I'm not great with server owning
