### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by muddup** [Xibalba/ZHorse#117]
## Question

Is there going to be an update for the 1.14?
Great plugin!!!!

**Comment by Zedd7** [comment]
It should come soon or later yes, but I can't give any date estimation. It depends on what's left to do for 1.8.1 and if any additional work is required to port it to 1.14.

Did you try running ZHorse 1.8.0 on a 1.14 Spigot/Paper server ? Did anything break ?

**Comment by muddup** [comment]
Sounds good. So far I have not had any issues with Zhorse, but we haven't really checked it all out. I will start running through what we have and let you know if anything comes up.
Thanks,
Muddup
