### ISSUE TITLE
/zh list

### ISSUE THREAD

**Issue by devgio0507** [Xibalba/ZHorse#118]
### What are you trying to do ?
/zh list
### What is the expected behavior ?
show me a list of my owned horses
### What is the actual behavior ?
nothing appears and i get a warning message in console
Description of the actual behavior goes here.
### How to reproduce the bug ?
1. do /zh list
2. nothing happens

### Console output 
https://pastebin.com/RGiWMCbW
Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !

## Environment specifications

- windows

- Java version : 9

- Server version : 1.12.2

- ZHorse version : 1.8.0

- Database :  SQLite

**Comment by Zedd7** [comment]
> Server version : 1.12.2
> ZHorse version : 1.8.0

ZHorse 1.8.0 is designed to run on 1.13 servers
You should either upgrade Spigot or downgrade ZHorse to version 1.7.0 (but then, only limited support will be provided).
