### ISSUE TITLE
/Zh list

### ISSUE THREAD

**Issue by devgio0507** [Xibalba/ZHorse#119]
### What are you trying to do ?
/zh list

### What is the expected behavior ?
display a list of my horses
### What is the actual behavior ?
nothing appears

### How to reproduce the bug ?

1. do /zh list

### Console output 

https://pastebin.com/7Q139irG

## Environment specifications

- Operating system : Windows

- Java version : 8

- Server version : 1.12.2

- ZHorse version : 1.7

- Database : Zhorse.db

**Comment by devgio0507** [comment]
Also, in issue #118 you said that zhorse 1.8 was the issue and i need 1.7 so i changed it however it still doesn't work.

**Comment by Zedd7** [comment]
Hi, sorry for the long delay but I didn't have time to provide support for ZHorse.
I don't have much more now so, if you still have this issue, I suggest to upgrade to Spigot 1.14.4 and [ZHorse 1.8.1 snapshot 3](https://www.spigotmc.org/threads/zhorse.45692/page-26#post-3412954).
If the issue persists, feel free to open this issue again (just edit the info) and I'll look into it.
