### ISSUE TITLE
Missing Horse Bug

### ISSUE THREAD

**Issue by taberruu** [Xibalba/ZHorse#12]
Some players want to teleport their horse to himself, but the horse is not found (it is still in the database)

(Latest Spigot 1.10 release & ZHorse 1.6.1)

**Comment by Zedd7** [comment]
This is an old bug that is only occurring on some servers (not on mine unfortunately) and that I wasn't able to fix for now.

What is happening is that ZHorse looks for the horse called with /zh here in the last chunk it was seen in, but for some reason (ZHorse malfunction, other plugin interference, spigot issue?) it disappeared from this chunk.
As ZHorse keep all claimed horses in memory as long as they are loaded, something must happen in that chunk when ZHorse is disabled or when the chunk is unloaded.

If you have a plugin that manage entities or chunks in an usual way, please tell me. (Plugins that remove stacked entities or the WE's /butcher command make this bug happen for example)

Note that "lost" horses can be retrieved if they were just moved to another chunk and that you can see them.
Also, does it happen all the time (that would help) or occasionally ? Updating to Minecraft 1.11 and ZHorse 1.6.2 would help.

**Comment by Zedd7** [comment]
I forgot to mention (same for [#11](https://github.com/Xibalba/ZHorse/issues/11)) : You can switch to the old teleportation method (see Settings section of config) which use the Spigot API to see if it fixes your issues.
