### ISSUE TITLE
error when enabeling on 1.14.2

### ISSUE THREAD

**Issue by thunderlight411** [Xibalba/ZHorse#120]
### What are you trying to do ?
When starting the server the following error messages shows up
https://pastebin.com/L70C3GSQ
config file / folder is not created

### Console output 
Full log : https://pastebin.com/d75a4Xy3 
Error when enabling : https://pastebin.com/L70C3GSQ

## Environment specifications

- Operating system : CentOS 5.

- Java version : 8

- Server version : git-paper-55 (MC:1.14.2)

- ZHorse version : 1.8.1 snapshot 3

- Database : sqlite is planned not ready configured because of the error

**Comment by thunderlight411** [comment]
When i mirror a serverconfig, i got the following error 
https://pastebin.com/P4RhvviB
Same host and same version of zhorse

**Comment by Zedd7** [comment]
I didn't have time to try to reproduce your issue yet but your second log says that your ZHorse version is 1.8.0, not 1.8.1 snapshot 3.

**Comment by Zedd7** [comment]
Do you still have this issue with Spigot 1.14.4 and ZHorse 1.8.1 snapshot 3 ?
