### ISSUE TITLE
TabCompletion Error

### ISSUE THREAD

**Issue by thunderlight411** [Xibalba/ZHorse#125]
### What are you trying to do ?
I'm traying to type /zh(space) and this gives a internal error 

### How to reproduce the bug ?

1. login
2. Start typing command /zh (Space)
3. See error in console and in game

### Console output 

https://gist.github.com/thunderlight411/ebdbe89f74c80acadbeadc35fcfc3d1f

## Environment specifications

- Operating system : Linux (CentOS 8)

- Java version : 8

- Server version : 1.14.4 PaperSpigot 

- ZHorse version : 1.8.1 snapshot 3

- Database : SQlite

**Comment by Zedd7** [comment]
@thunderlight411 I tried to reproduce this on different Spigot and Paper builds but it works just fine for me. Do you have any additional detail to provide or do you have an idea of what is causing this ?
