### ISSUE TITLE
Friend list issue

### ISSUE THREAD

**Issue by Remski01** [Xibalba/ZHorse#126]
### What are you trying to do ?

Go on a horse where it should be enable to go on. (beinig added as friend)

### What is the expected behavior ?

Beinig enable to go on it.

### What is the actual behavior ?

Not beinig to go on it, with the error that i am not added as friend. (horseBelongsTo:)

### How to reproduce the bug ?

This is were some debug stuff come in place, because on our test server this behavior isnt happening.

### Console output 

No error.

## Environment specifications

- Server version : Paper 1.14.4 (186)

- ZHorse version : ZHorse 1.8.1 snapshot 3

- Database : SQLite

**Comment by Remski01** [comment]
Turned out that it was because the player that want to sit on the horse also need to add the owner instead the owner only him. (what would be more logical imo)

Could you maybe look to change this? That only the owner need to add a user to allow the user to go on the horse? Or add a message that says that the user need to add the owner too to sit on it.

Note: I'm going do some retesting as i'm not sure if was the same on the test server. As far i can remember this wasnt needed on the test server. (that the user need to add the owner), however, i have unfortunately have deleted the log about this on our discord server, that's why i need to retest some stuff. **So will post the testing in here.**

**Comment by Zedd7** [comment]
> That only the owner need to add a user to allow the user to go on the horse?

That's how it was designed but it was bugged, thanks for the report ;)
