### ISSUE TITLE
Not allowing non OP players to ride

### ISSUE THREAD

**Issue by Devynelle** [Xibalba/ZHorse#128]
Hello,
 There is an issue with players mounting horses. Players that are not OP cannot mount any horses. I've tried them mounting unclaimed horses and claimed horses with share on and neither work. The player just gets kicked off the horse when they try to mount. Please get back to me about this issue ASAP. Thank you

**Comment by Zedd7** [comment]
Hello,

Is there an error in console ? A message in the chat ?
What is your ZHorse version ? Spigot/Paper version ?
Do you have plugins that might interfere with ZHorse ?

Please provide [more details](https://github.com/Zedd7/ZHorse/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). I won't be able to fix your issue if I can't reproduce it or isolate it precisely.
