### ISSUE TITLE
Errors since newer paper builds

### ISSUE THREAD

**Issue by Sikatsu** [Xibalba/ZHorse#129]
## Bug report
https://pastebin.com/0m5bREVz

## Environment specifications

- Operating system : Windows

- Java version : 8

- Server version : 1.14.4 Paper

- ZHorse version : 1.8.1 snapshot

- Database : default

**Comment by Zedd7** [comment]
@Sikatsu Is this still happening with latest Paper build ? (230)
If so, with which kind of horse ? It seems that the type (llama, donkey, ...) of the horse is not recognised.

**Comment by Sikatsu** [comment]
Hmm, don't think so!

**Comment by Zedd7** [comment]
:+1:
