### ISSUE TITLE
non-vanilla MAX and MIN speed, jump size, and health

### ISSUE THREAD

**Issue by tsulh** [Xibalba/ZHorse#13]
I noticed that this mod changes the vanilla thresholds when I saw how ridiculously fast is the horse with 100% speed, and a house with 100% jump size jumps so high that it hurts itself badly. Also, the mod allows to spawn a horse that cannot walk at all. The worst part that this threshold mismatch makes it hard to access the naturally spawned horses.

So I suggest to replace the thresholds to vanilla ones by changing the piece of https://github.com/Xibalba/ZHorse/blob/ad916baf1de4d7e0fed4fc1d749e591abf2de081/src/eu/reborn_minecraft/zhorse/managers/HorseManager.java#L29 to the following (values are from the http://minecraft.gamepedia.com/Horse#Statistics):

public static final double MIN_HEALTH = 15.0;
  public static final double MIN_JUMP_STRENGTH = 0.4;
  public static final double MIN_SPEED = 0.1125;
  public static final int MIN_LLAMA_STRENGTH = 1;
  
  public static final double MAX_HEALTH = 30.0;
  public static final double MAX_JUMP_STRENGTH = 1.0;
  public static final double MAX_SPEED = 0.3375;
  public static final int MAX_LLAMA_STRENGTH = 5;

**Comment by Zedd7** [comment]
The purpose of using Bukkit thresholds instead of those of Minecraft is to allow server admins to make some fun events with horses : jumping contests, archery targets and so on.
So I may add a config option to switch to vanilla values but the actual ones will remain available.

However, I don't understand why it bothers you to have unrealistic thresholds available with /zh spawn. Did you allow your players to use it ?
If not, keep in mind that you can simply skip any value in /zh spawn like this : 
- /zh spawn
- /zh spawn 20::
- /zh spawn 20::30%
- /zh spawn :20:30
- and so on

**Comment by tsulh** [comment]
> The purpose of using Bukkit thresholds instead of those of Minecraft is to allow server admins to make some fun events with horses : jumping contests, archery targets and so on.

Ok I see, thanks for pointing out.

> So I may add a config option to switch to vanilla values but the actual ones will remain available.

That would be great. Seing vanilla values allows to immediately estimate how good is the horse, and when those 100% are between 20-30, it's 10 times less precise. Yes, the players on our server can see those values (for the above reasons). No one is allowed to use '/zh spawn'. :)

P.S. Thanks for the mod, I had a lot of fun and roleplay because an unexpected horse replication on 1.11 yesterday! I can't replicate, so I don't create an issue. (I've seen in another issue that you only got reports about replications on <1.11)

**Comment by Zedd7** [comment]
> Seing vanilla values allows to immediately estimate how good is the horse, and when those 100% are between 20-30, it's 10 times less precise.

This makes sense, I will add the option.

**Comment by tsulh** [comment]
Great, thanks. Waiting for the update!

**Comment by Zedd7** [comment]
Is it fine for you if I commit it here without releasing a .jar ?
(Might take a week anyway, I'm really busy atm.)

**Comment by Zedd7** [comment]
Will be available by default with release 1.6.3 (you still need to add the option in config).
