### ISSUE TITLE
Error /zh claim

### ISSUE THREAD

**Issue by Woutdv** [Xibalba/ZHorse#131]
If i tamed a horse and I type /zh claim (Name) i get this error

> [14:22:32 WARN]: java.lang.reflect.InvocationTargetException
>.... [14:22:32 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>.... [14:22:32 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>.... [14:22:32 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>.... [14:22:32 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.managers.CommandManager.onCommand(CommandManager.java:47)
>.... [14:22:32 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [14:22:32 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [14:22:32 WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3593.0000000060096290.run(Unknown Source)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
>.... [14:22:32 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
>.... [14:22:32 WARN]: at java.lang.Thread.run(Thread.java:819)
>.... [14:22:32 WARN]: Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
>.... [14:22:32 WARN]: at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
>.... [14:22:32 WARN]: at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)
>.... [14:22:32 WARN]: at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:32)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:307)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:47)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.commands.AbstractCommand.hasReachedClaimsLimit(AbstractCommand.java:339)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.commands.CommandClaim.execute(CommandClaim.java:43)
>.... [14:22:32 WARN]: at com.github.zedd7.zhorse.commands.CommandClaim.<init>(CommandClaim.java:24)
>.... [14:22:32 WARN]: ... 24 more

**Comment by Zedd7** [comment]
You need to use a permission plugin supporting permission groups.
