### ISSUE TITLE
Shared, then Unshared horse can still be ridden by anyone after unsharing

### ISSUE THREAD

**Issue by gmalone** [Xibalba/ZHorse#132]
## Bug report
A horse shared to everyone, then unshared (by repeating the share command) can still be ridden by anyone, though its info now says it is Restricted again.

### What are you trying to do ?
Make an unshared horse not rideable by anyone unauthorized.

Description of the task to be done goes here.

### What is the expected behavior ?
A restricted horse (that was previously unshared) should not be rideable by the public.

Description of the expected behavior goes here.

### What is the actual behavior ?
Anyone can still ride the unshared/restricted horse

Description of the actual behavior goes here.

### How to reproduce the bug ?

1. Step 1
2. Step 2
3. ...

### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !

## Environment specifications

- Operating system :
Win 10

- Java version :

- Server version :
Paper 1.14.4 (final version)

- ZHorse version :
v.1.8.1

- Database : SQLite

**Comment by Zedd7** [comment]
> What are you trying to do ?
Make an unshared horse not rideable by anyone unauthorized.

For this you should use `/zh lock` instead. Your confusion comes from the fact that horses have 3 'levels' of locking : shared < restricted < locked.
See [this page](https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks#what-are-the-different-modes-of-horse-protection-) for more information on the security levels ;)

**Comment by gmalone** [comment]
Thank you.
