### ISSUE TITLE
Adds

### ISSUE THREAD

**Issue by BroganMC** [Xibalba/ZHorse#136]
Hey! I wasn’t sure how to get in contact with you Zedd, but I was wondering if I could code in some extra things for my server into your plugin? You would get credit for the plugin and the plugin name would not be changed. 

If not, I have a couple suggestions. 
I think adding breeds, gender, and age would be awesome. It wouldn’t change the horse’s stats or anything, but when you do /zh info you could view the horse’s age, gender, and breed for role play purposes. 
Also, there can be an OP override that allows you to set the gender, breed, and age with something like /zh set breed/gender/age 
And for breeds, maybe there can be a folder where the person can add breeds, that way the person using the plugin can add whatever horse breeds they want as options in game. 
Hopefully you take this into consideration!

**Comment by Zedd7** [comment]
Hello @BroganMC,

Yes sure, be my guest ;)
You can fork this repository and start working on your own version of ZHorse and then either distribute it on your own, or submit pull requests to merge your changes into my version of ZHorse.

I'm definitely not much activate anymore on this project so don't wait for my approval for anything, you're free to customise ZHorse all you want as long as you don't sell it.
You can also take a look at the [open enhancement tasks](https://github.com/Zedd7/ZHorse/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) if you're looking for new challenges

About you idea of setting the breed, age and gender, you might want to look into `/zh edit` which already has a framework for the edition of live horses.

Good luck & Have fun

**Comment by Zedd7** [comment]
I'm closing this since it has been answered but feel free to re-open should you have any question (I'm inactive, not dead) and to keep me updated on your project.

**Comment by BroganMC** [comment]
Hey!
 So I’m having trouble finding a developer to hire for the project I had in mind that I previously presented, I was wondering if you would be able to add my ideas into the plugin? We are willing to pay, the issue is just that we need a horse plugin very short notice with no developer available.
 Thank you for your consideration!

**Comment by Zedd7** [comment]
Hi,
Sorry but this project is only a hobby for me. I wouldn't want to get paid to work on it, especially on demand. I prefer investing some of my free time when I feel like it and try to deliver a good product as a service to the Minecraft community.
