### ISSUE TITLE
permissions bug? or Iam doing something wrong?

### ISSUE THREAD

**Issue by altair1cz** [Xibalba/ZHorse#14]
Hi guys I got little bit trouble run this plugin on newest craftbukkit 1.11 but even if I setup permissions for groups player or admins correctly its not working  ingame its saying I still dont have permission use this comand. Neither zh.use or zh.* .Iam using essentials group manager.

**Comment by Zedd7** [comment]
Do you have the permission to do "/zh list" if you are OP ?

**Comment by altair1cz** [comment]
nevermind I fixed it by swithing to Pex guess group manager is really bugged for 1.11.

**Comment by Zedd7** [comment]
Thanks for the info, enjoy !
