### ISSUE TITLE
Bug with Zhorse

### ISSUE THREAD

**Issue by Blamo27** [Xibalba/ZHorse#15]
Hello,

We are planning on installing your plugin on our server. However, currently, it is simply unusable due to a simple issue : when a player tries to teleport his horse to him while in a "no mob-spawning" zone, the horse is -of course- not teleported (this is normal), but the result is that the horse can't be found again on the server afterwards, making it impossible to teleport elsewhere. In other words, doing the /zh here command in a no mob-spawning zone makes your horse vanish from the server, all you can do next is delete it. This is due to the fact that your plugin seems to only teleport an existing horse frome somewhere in the server to somewhere else, it doesn't save its data to the database. As a result, ANY bad spawning of the horse upon teleportation causes it to be lost forever. On a heavily world guard protected server, which is the case of most roleplay servers, that makes this plugin unfortunately unusable.

Therefore, we would need a system that actually saves the horse's data in the database, much like the Horses plugin did back in the days, so even if something goes wrong, the horse can still be invoked since it is not its actual physical existence that counts, but its data in the databse. That would, by the way, allow you to easily make an option to recover the horse after its death (otherwise, with such an option disabled, the dead horse would simply be erased from the database). You would of course need to make sure that re-invoking an existing horse would not duplicate it, and therefore that it would erase the "previous copy" of the horse to create a new one to your location.

Thank you.

**Comment by Zedd7** [comment]
Hello,

Did you try setting "block-plugin-spawning" to "false" in WorldGuard config ?
If it doesn't work, you can set "Settings.use-old-teleportation-method" to "true" in ZHorse config to switch to the Bukkit's teleportation method instead of ZHorse's custom one. (By default, this alternative teleportation method is used to fix a Bukkit bug)

Does it helps ?

**Comment by Blamo27** [comment]
We can't do any of these options, because we can't have players teleporting their horses where they shouldn't be able to : for example we have arenas, we don't want players to be able to teleport their horse in the middle of the arena ! Also, we are partly a PVP server, but we forbid usebugs to enter a base : with the methods you suggested, we are able to teleport the horse into a wall to pass through it, which is something one of our plugins normally blocks.

**Comment by Zedd7** [comment]
Well, I plan to implement WorldGuard API and add related config options someday but it won't come before February.

So, currently, you only option is to disable ZHorse or deny the zh.here permission.
