### ISSUE TITLE
Zhorse does not release all horses in possession

### ISSUE THREAD

**Issue by MrKiller01** [Xibalba/ZHorse#17]
As i stated on spigot:
Hi,
Like the plugin except there are a few hickups i noticed. I had a horse named Pegasus, i asked for it, could not be found in database, so i tried abit, eventually i used /zh admin clear Pegasus, but that did not work. Why not???
Eventually i used TAB-key to give options after clear, and it was my own name. Ok, so be it i thought. Every horse was cleared from me. Then i typed /Zh list and guess, still two horses were attached to me, even the one that does not exist.
Question, if it is possible an alternative for /zh admin clear <player.> (Even though the help says that it clears a horse from the database, not the other way around.)
If you are at it at that time, think of a more graphical user interface, that can also interact and maintain the horses from others...
Thanks for nice job....

I deleted the .db file and then they were gone, but so were all other appointed horses...

**Comment by Zedd7** [comment]
As stated on Spigot : 

You really need to update your ticket in order to make it easy for anyone to :

1. Understand what it is about.
2. Set up the same environnement as yours (Spigot version, ZHorse version, database type, ...)
3. Reproduce the bug by following the steps

**Comment by MrKiller01** [comment]
Hi, i do not know how to update this ticket, i thought that i gave all info, but if you think it is not necessary to give me a chance to explain if you don't understand, fine by me...

**Comment by Zedd7** [comment]
There is an edit button in the top right corner of your ticket which you are free to use, and I will re-open your ticket as soon as it meets the requirements to be an open ticket.

By the way I waited 2 weeks after warning you about your ticket's validity before closing it, and closing a ticket is different from deleting it.

**Comment by MrKiller01** [comment]
Sorry for being an ass, i have had a bunch of other problems that were more urgent. Sorry for that.
Its closed also because i lost track of the problem and will go to forum if i have another Q...
