### ISSUE TITLE
[minor bug] two message when horse is tamed

### ISSUE THREAD

**Issue by Oruss7** [Xibalba/ZHorse#19]
version: 1.6.3
other: I'm OP
reproduce: i mount a untamed horse, when it is tamed, i see the zhorse message (.../zh claim to claim this horse ...) 2 times. 

thanks

**Comment by Zedd7** [comment]
Does it still happen after server restart ?

**Comment by Oruss7** [comment]
yeah

**Comment by Zedd7** [comment]
I could reproduce it but, as this is not urgent, the fix might takes a few weeks to come because I'm currently in an exams session

**Comment by Zedd7** [comment]
Hello, I updated my main et test servers to the very last Spigot build and I can't reproduce this bug anymore, can you ?
(This is perfectly normal because there was no way that ZHorse was causing this bug)
