### ISSUE TITLE
Kick a player off the horse, before logout.

### ISSUE THREAD

**Issue by taberruu** [Xibalba/ZHorse#21]
Hey,
I've a feature request.

Can you add a mechanic to kick a players from a Zhorse-Horse, before they logging out?

It fixes the Problem:
By logging out, they take the horse with them, this means that the owner of the horse can not find it.

**Comment by Zedd7** [comment]
Yup, can do.
I was hoping for a fix of that bug from Mojang but it's obviously not done yet.
