### ISSUE TITLE
Can't claim horses!!

### ISSUE THREAD

**Issue by cherokeelover4210** [Xibalba/ZHorse#23]
I cannot seem to claim horses, I can spawn custom horses and it works fine, but every time I do /zh claim, the message disappears, please help!

**Comment by Zedd7** [comment]
(For the record)
ZHorse version : 1.5.1
Minecraft version : 1.9.0

**Comment by Zedd7** [comment]
Do you have any ZHorse related errors in console at server start up or when you execute /zh claim ?

**Comment by cherokeelover4210** [comment]
It says:

[Server] WARN at
eu.reborn_minecraft.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:37)

I do not know if that is a bad thing, since this is my first time owning a server, I just figured I'd let you know about this, because this pops up

**Comment by Zedd7** [comment]
Oh okay, then you may have made a configuration mistake ? Let's explore this possibility first.

1. First of all, rename ZHorse/config.yml in something else (like config_old.yml) and execute /zh reload. (Do not edit the newly created config.yml)
2. Spawn a new horse with an egg and tame it naturally (a ZHorse message should pop-up)
3. Mount this horse and execute "/zh claim -a" (you must be operator on your server)

Does it work ?

**Comment by cherokeelover4210** [comment]
So I just have completed the task, and the same problem occurs. I don't know if this has anything to do with it, but I am on a Macbook Air. I also do not know if its because I am using 1.5.1 on 1.9, but the bukkit page said it was for 1.9, so I don't know if that is also an error

**Comment by Zedd7** [comment]
Well, with MC 1.9 you can use ZHorse 1.6.1 (not above because MC 1.11 creates conflicts with older versions). However it should work with ZH 1.5.1 on MC 1.9.

Now, when you say that "the message disappears", what message is that ?
- Congratulation ! You can now use /zh claim (name) if you want.

Or

- <horse>was successfully claimed.

**Comment by cherokeelover4210** [comment]
The congratulations! message shows up, and I do /zh claim (name) and nothing shows up. It doesn't even say "could not be claimed" or anything.

**Comment by Zedd7** [comment]
You can simply use /zh claim (without the name) and it should assign it a random name.
Any errors in console when you enter that command ? (copy everything in console after "...executed /zh claim..." on pastebin.com)

**Comment by cherokeelover4210** [comment]
This is everything after I executed the command:
22.01 10:36:51 [Server] WARN java.lang.reflect.InvocationTargetException
22.01 10:36:51 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
22.01 10:36:51 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
22.01 10:36:51 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
22.01 10:36:51 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
22.01 10:36:51 [Server] WARN at eu.reborn_minecraft.zhorse.managers.CommandManager.onCommand(CommandManager.java:42)
22.01 10:36:51 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
22.01 10:36:51 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
22.01 10:36:51 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:624)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1298)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1158)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
22.01 10:36:51 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22.01 10:36:51 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635)
22.01 10:36:51 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539)
22.01 10:36:51 [Server] WARN at java.lang.Thread.run(Thread.java:745)
22.01 10:36:51 [Server] WARN Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
22.01 10:36:51 [Server] WARN at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
22.01 10:36:51 [Server] WARN at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726)
22.01 10:36:51 [Server] WARN at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
22.01 10:36:51 [Server] WARN at eu.reborn_minecraft.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:103)
22.01 10:36:51 [Server] WARN at eu.reborn_minecraft.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:37)
22.01 10:36:51 [Server] WARN at eu.reborn_minecraft.zhorse.commands.Command.hasReachedMaxClaims(Command.java:244)

**Comment by Zedd7** [comment]
pastebin.com please

**Comment by cherokeelover4210** [comment]
I do not know how to do that.

**Comment by Zedd7** [comment]
It's quite simple. Go to pastebin.com, paste your logs in the big white box and hit the Paste button, then share the link here.
That way, server logs don't take too much place in this ticket and are presented in a more readable way

**Comment by cherokeelover4210** [comment]
Okay, heres the link then:  http://pastebin.com/4ymR08bw

**Comment by Zedd7** [comment]
Thanks, it appears quite clearly when reading the logs that SuperPerms is causing this bug.
If you read the logs from lines 29 to 23 you can see that ZHorse submit a request to Vault that fails to fulfill it because SuperPerms raises an exception.

As you are just starting with your server, I suggest that you try a different permission plugin (like [PermissionBukkit](https://dev.bukkit.org/projects/permbukkit)) because this is not ZHorse that is causing this, and it could very well happen with other plugins.
