### ISSUE TITLE
zh spawn fails to parse some horse colors

### ISSUE THREAD

**Issue by lfreijo** [Xibalba/ZHorse#26]
When using the /zh spawn command some colors fail. Example:

/zh spawn horse none black

Gives the error:
[ZHorse] black is not a valid argument for /zh spawn

It looks like the issue is in the CommandSpawn class line 83. It looks to me that the horse color is parsed correctly, but then the Llama color is attempted to be parsed. This fails as black is not a valid llama color so parsed is set to false. 

I don't see an easy way to fix this other than restructuring the parseArguments method to call different color parsing methods based on the variant.

**Comment by Zedd7** [comment]
I will fix that as soon as I can but I still have the next snapshot to finish and I am super busy right now :/

**Comment by lfreijo** [comment]
No problem. I was playing around with the code to see if I could fix it, but I was having issues building the jar. I don't have much experience with java and found the spigot wiki page for building plugins a little lacking. Do you have any instructions or a link that shows how to setup and build this plugin?

**Comment by Zedd7** [comment]
This plugin is actually very easy to build compared to others.
The simplest way would be to open it in Eclipse then right-click on it > export > Java/JAR file > Finish (default options should be good)

**Comment by Zedd7** [comment]
Hello, if you are currently running a snapshot of ZHorse 1.6.4, remember to drop tables "horse_stats", "horse_inventory" and "inventory_item" (if you have them) before updating to the final release of ZHorse 1.6.4 !

**Comment by lfreijo** [comment]
Thanks for letting me know! I am actually still using 1.6.3 (with my change) on my main server until you finish up everything for 1.6.4.

**Comment by Zedd7** [comment]
Oh ok, then you don't need to do anything !
