### ISSUE TITLE
Chat spam in 1.9

### ISSUE THREAD

**Issue by PIE-yt** [Xibalba/ZHorse#3]
ZHorse prints the same lines repeatedly in chat, when interacting with a horse. ("That horse belongs to player" prints about 8 times.)

(Also your tickets link on bukkit dev is 403'ing)

Thanks for your time :)

**Comment by Zedd7** [comment]
Hello, could you provide more details about the issue ?
Does it happen with all horses, all players and all ranks. Does it happen when hand is empty/holding an item/both, etc.

Also, make sure to run the latest version of Java, Bukkit/Spigot and ZHorse !

(Tickets link fixed, thanks)

**Comment by PIE-yt** [comment]
Hi,
Issue is fixed in Spigot 1.10
Thanks!

The issue was any time a player clicked a horse, any feedback in chat (such as it belonging to someone else) was shown 8 times rather than just once.

**Comment by Zedd7** [comment]
Ok, maybe was it another plugin spamming click events or something^^
