### ISSUE TITLE
Exceptions raised when different events are fired

### ISSUE THREAD

**Issue by MicraMC** [Xibalba/ZHorse#34]
Hello, i'm running the new released version of zhorse on a 1.11 server however in the CONSOLE I am getting these errors:
https://paste.md-5.net/femaqigito.vbs 
https://paste.md-5.net/tilokeyude.vbs 

I also believe this is the source of my server crashing so if this could be fixed, that could be great :+1: 
The zhorse config is:
https://paste.md-5.net/xetijaxeno.vbs
I took out the info for MYSQL but i am using it 

Thank you so much =D

**Comment by Zedd7** [comment]
> I took out the info for MYSQL but i am using it

Be careful that the config option Databases.type must be set to "MySQL" in order to use it. Configuring Databases.mysql-config is not enough !

**Comment by Zedd7** [comment]
It seems that the error is related to my previous comment : the database was not selected properly when ZHorse was being loaded.

Could you provide me the logs from the moment your server is started (or ZHorse is reloaded) ?

**Comment by MicraMC** [comment]
https://paste.md-5.net/kaxesehego.vbs
When i reload config ^
Tysm :)

**Comment by Zedd7** [comment]
> 31.03 05:24:07 [Server] INFO intermediate:
31.03 05:24:07 [Server] INFO in 'string', line 105, column 3:
31.03 05:24:07 [Server] INFO expected <block end>, but found BlockMappingStart

Try removing one space before group names on lines 103, 110, 115.
Then execute /zh reload (don't forget about warning) and see what happens

**Comment by MicraMC** [comment]
https://paste.md-5.net/horoguguri.vbs

That's what came up ^

**Comment by Zedd7** [comment]
Ok. Then the easiest way is to rename your current config to "config_old.yml", execute /zh reload, and configure again the newly generated "config.yml" as you want, but with great care !

This issue is actually not ZHorse related. You simply made a mistake in your config :p

PS : Could you edit your comment on Spigot to state that this is resolved ?

**Comment by MicraMC** [comment]
Wow aha thank you so much, fixed :p. You're a hero and keep up the awesome plugin and support <3

**Comment by Zedd7** [comment]
Thanks :p 
Could I visit your server ? I'm curious to see how ZHorse is being used :)
