### ISSUE TITLE
Players have to relog to claim horses.

### ISSUE THREAD

**Issue by MicraMC** [Xibalba/ZHorse#40]
Hey, it's me again :p. Whenever a new person joins my server, there claim limit is 0/0 and they have to relog to get claims. If this could possibly be changed that would be amazing as it is hard to explain to the players and quite annyoing. I know the perms etc. are working as, as soon as the player relogs it changes and they can claim.
Thank you :)

**Comment by Zedd7** [comment]
That is not intended that way, players should be able to see their claims with /zh list at any time.
Could you provide more details ? (server version, Minecraft version, plugin version, any error in console, config, ...)

**Comment by MicraMC** [comment]
Server version: 1.11 {can be used with 1.11.2 tho}
Minecraft version: 1.11.2
Plugin version: Zhorse 1.6.5 {newest}
No error in console
Config: https://paste.md-5.net/wuhomiwoni.vbs 
The permissions are definetly in the permissions list (Using PEX)

**Comment by Zedd7** [comment]
I could reproduce it, fix planned for 1.6.6.
