### ISSUE TITLE
/zh here error

### ISSUE THREAD

**Issue by MicraMC** [Xibalba/ZHorse#46]
Hey there,
I'm having an issue where whenever a player does /zh here, it says their horse teleports to them but it is invisible/not there. Whenever you do /zh tp it teleports you to the spot but there is not horse.
This is the error that comes up in the CONSOLE:
`17.04 18:02:28 [Server] WARN Caused by: java.lang.NullPointerException
17.04 18:02:28 [Server] WARN at java.lang.Thread.run(Thread.java:745)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
17.04 18:02:28 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17.04 18:02:28 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
17.04 18:02:28 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
17.04 18:02:28 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
17.04 18:02:28 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
17.04 18:02:28 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
17.04 18:02:28 [Server] WARN at com.gmail.xibalbazedd.zhorse.managers.CommandManager.onCommand(CommandManager.java:40)
17.04 18:02:28 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
17.04 18:02:28 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
17.04 18:02:28 [Server] WARN at sun.reflect.GeneratedConstructorAccessor184.newInstance(Unknown Source)
17.04 18:02:28 [Server] WARN java.lang.reflect.InvocationTargetException
17.04 18:02:28 [Server] INFO foxfire9000 issued server command: /zh here`

Im using Zhorse 1.6.6 and minecraft 1.11.2
Also I have the new teleportation method enabled

**Comment by Zedd7** [comment]
Hi, please provide a pastebin.com link containing the full error log, because this is not readable

**Comment by MicraMC** [comment]
Hold on nevermind I found the error, a plugin was conflicting. Thanks for help =D
