### ISSUE TITLE
Error with most zhorse commands

### ISSUE THREAD

**Issue by MyPonyBobby** [Xibalba/ZHorse#47]
In minecraft version 1.11.2 using newest update. It appears I have the same problem as another person who submitted a thread on the Spigot site.

In console:
https://paste.md-5.net/jojosipune.avrasm

**Comment by Zedd7** [comment]
Are you using MySQL ?
It could be that your MySQL server is outdated and needs an upgrade, as I am using MySQL57's features in ZHorse 1.6.6.

**Comment by MyPonyBobby** [comment]
I'm not using MySQL or SQLite

There is aLSo no error when i do /zh reload

**Comment by MyPonyBobby** [comment]
ALso there is no error when I do /zh reload.

**Comment by Zedd7** [comment]
Which ZHorse and Spigot versions were you using before updating ?

**Comment by MyPonyBobby** [comment]
I was using spigot 1.11.2 and zhorse snapshot 1.6.6 snapshot 3 
I reloaded the config and language files as well as the server

Now I'm using 1.11.2 and zhorse 1.6.6

**Comment by Zedd7** [comment]
I will try to reproduce this on my test server.
In the meantime, upgrade your server to the very last Spigot version.

**Comment by MyPonyBobby** [comment]
Thank you, it's on lastest version of spigot. It doesn't /zh claim, /zh reload, /zh settings or /zh help but as soon as you try to do /zh here or /zh tp nothing happens and an error comes up in CONSOLE. Also /zh share and /zh friend causes errors

**Comment by Xibalba** [comment]
You have indeed the same issue, so I mark this issue as a duplicate of #48 and suggest you to follow the same instructions ;)

**Comment by Xibalba** [comment]
Duplicate of #48

**Comment by Zedd7** [comment]
You have indeed the same issue, so I suggest you to follow the same instructions as those given in the linked issue ;)

Duplicate of #48

**Comment by MyPonyBobby** [comment]
Zhorse 1.6.7 fixed the issue so far! Thank you so muc ;) No errors in console anymore

**Comment by Zedd7** [comment]
Yes but those errors occurred when ZHorse was trying to spawn missing horses, which should not have happened in the first place. It means that some horse could not be found in their chunk, that is something that would happen in you regen the world or the chunk for example.

So feel free to open a new issue describing how I can reproduce this.
