### ISSUE TITLE
Horse genders

### ISSUE THREAD

**Issue by P3NGU1N101** [Xibalba/ZHorse#51]
I think an awesome idea would be to add genders and a gelding tool. Also making genders effect breeding. Another idea would be horse ages.

Also natural breeding so like if you put a mare and stally together, there is a chance they may breed.

**Comment by Zedd7** [comment]
Sorry but such modifications to the vanilla breeding won't happen with ZHorse, as this plugin focuses on managing et protecting vanilla horses with only minor changes to the way vanilla horses behave.
