### ISSUE TITLE
Unregister a horse does not clear the tamer field

### ISSUE THREAD

**Issue by DoreK333** [Xibalba/ZHorse#52]
The "/zh free" command does not turn a horse into an unmarried one.
The same is true of the "/zh sell" command

**Comment by Zedd7** [comment]
There may be errors on the console then, check if you have any

**Comment by DoreK333** [comment]
There are no errors.
The point is that as the horse is tamed it is attributed to the player who tamed him and after the command "/ zh free" the horse is still tame to the player.

**Comment by Zedd7** [comment]
Oh ok !
Then I'll change the topic so I remember what this is about^^

**Comment by Zedd7** [comment]
It appears that it is not possible to remove a tamer (owner) and keep the horse tamed at the same time.
However, I would like to keep freed horses tamed as players could want to free their horses and claim them again later, without having to tame them again too.

In which practical case would you need the tamer field to be cleared when using /zh free ?

Anyway, I will make the owner change when a horse is bought, claimed or given.
