### ISSUE TITLE
Issues with zhorse [Does anyone else have issues like this or similar?]

### ISSUE THREAD

**Issue by P3NGU1N101** [Xibalba/ZHorse#54]
Hey,
I'm having more issues:
a) /zh list is bugging out, it says like 12/20 but there are only 2 horse names listed. PLEASE FIX THIS. There is no error in console however
b) players are having issues where zhorse is causing horses to die on /zh here
c) zhorse appears to be causing corrupted chunks (anyone else happening these problems?)
d) claim permissions still DO NOT work? Adding permissions does not increase claim limit even if the player relogs.

Please help and is anyone else having these issues or similar?

USING: Zhorse 1.6.6
MC VERSION: 1.11.2/1.11

**Comment by Zedd7** [comment]
Hello, please note that I'm currently very busy until mid-June and will thus not be able to work fully on this until then.

In the meantime, I can still make this ticket progress a little : 
a) Do you use MySQL or SQLite ? Does it happen to every player or just in some cases ? Can you provides the steps to reproduce this, or spot some inconsistances in the database ?
b) That is quite weird and I have never heard about it on any other server. However, you could try [this](https://github.com/Xibalba/ZHorse/wiki/Tips-&-tricks#horse-teleportation-bug).
c) ZHorse is not doing anything else on chunks than loading them, like a bunch of others plugins. Could you then describe this in more details ?
d) Consider reading [this](https://github.com/Xibalba/ZHorse/wiki/Tips-&-tricks#unexpected-limit-reached-message).

**Comment by P3NGU1N101** [comment]
ALl good, thanks.

a) I don't use MySQL or SQLite, should I?
b) Thanks 
c) I'm not sure if it is Zhorse, I was just wondering if anyone else had this when they had Zhorse plugin on. I never used to get corrupted chunks (chunks which if a player gets stuck, will restart the server) but when I added the zhorse plugin, it started and when i took zhorse off, it stopped.
d) Thank you

**Comment by Zedd7** [comment]
a) Actually you don't have a choice, ZHorse uses either SQLite (default) or MySQL
d) I gave you the wrong link, it should be [this one](https://github.com/Xibalba/ZHorse/wiki/Tips-&-tricks#unexpected-limit-reached-message).

**Comment by Zedd7** [comment]
Hello, I'm back and ready to work on ZHorse.
As there are several potential bugs reported in this issue, I will close this ticket and let you create new ones for each of your remaining issues with ZHorse.
