### ISSUE TITLE
"ZHorse is disabled on this world."

### ISSUE THREAD

**Issue by yaylivi** [Xibalba/ZHorse#55]
Hi, I am trying to use ZHorse on my world but every time someone types in a command, they recieve the message "ZHorse is disabled on this world." I have reinstalled it multiple times, disabled and re-enabled, reloaded, but nothing seems to work.

**Comment by Zedd7** [comment]
Hello, make sure that all the worlds in which ZHorse should be enabled are listed in the config : https://github.com/Xibalba/ZHorse/wiki/Config (see Worlds section)

By default, those worlds are "world", "world_nether" and "world_the_end"
