### ISSUE TITLE
Use Maven

### ISSUE THREAD

**Issue by jeffadev** [Xibalba/ZHorse#64]
## Feature request

Are you opposed to adding Maven to this project? I personally use Maven on mine, and it makes it very easy to add dependencies such as other plugin APIs and Spigot itself. When putting my pull request I had a hard time getting Spigot all hooked up.

**Comment by Zedd7** [comment]
I never considered it very useful fro this project as there is only a few fork and it has only 2 dependencies, including Spigot. But yes, I can do that.

**Comment by jeffadev** [comment]
Thanks, that would be extremely helpful to pickup and start developing.

I do understand and respect your reasoning for not including it thus far though.
