### ISSUE TITLE
Claiming still isn't working (a new message comes up)

### ISSUE THREAD

**Issue by cherokeelover4210** [Xibalba/ZHorse#66]
Hello!

I talked to you back in January, about how I couldn't claim horses? Well, I semi-fixed it.

I downloaded PermissionsEx for the ranks part of the server, but, when I reinstalled ZHorse again after that, I tried claiming horses, and it says, "Your claims limit has been reached." (even though it was my first time claiming a horse since the reinstallation.)

However, I didn't add the ZHorse perms. to the rest of the ranks, and I wanted your opinion on it as I really want to use ZHorse and I don't want to add the perm. nodes to the rest of them if won't help.

Thanks!

**Comment by Zedd7** [comment]
Hello, this is very likely because your permission group is not registered in ZHorse config. 
You should find all the required details here : https://github.com/Xibalba/ZHorse/wiki/Tips-&-tricks#unexpected-limit-reached-message
