### ISSUE TITLE
/zh spawn command vague, needs examples and more details

### ISSUE THREAD

**Issue by TheZenKitteh** [Xibalba/ZHorse#69]
Just saw the /zh spawn command and looked on the command reference and in game and it's not clear enough how to spawn a horse. My attempt to spawn a regular horse gave me a mule one time and a llama another time. Every other time was errors due to not being the right string of arguments.

I suggest giving some examples on the commands page on how to use this command and maybe link to a page with more information if such a page exists.

**Comment by Zedd7** [comment]
Good idea ! Links to the [Tips & tricks page](https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks) have been added for each complicated command.
