### ISSUE TITLE
Errors on server console at startup

### ISSUE THREAD

**Issue by SofieHL** [Xibalba/ZHorse#70]
## Bug report
The following errors appear on console at server startup:

https://pastebin.com/aUDP2N5G

## Environment specifications

- Operating system :  Linux

- Java version : 8

- Server version : Spigot 1.11.2

- ZHorse version : 1.6.8
- Database :  SQLite

**Comment by Zedd7** [comment]
Hi, sorry for not having been available at the time. Please open this issue again if you are still encountering it.
