### ISSUE TITLE
Hard Crash - https://pastebin.com/K9iqj4SP

### ISSUE THREAD

**Issue by larrycatania** [Xibalba/ZHorse#71]
### What are you trying to do ?

--PLayer trying to TP Horse

### What is the expected behavior ?

-- Horse TP to Player

### What is the actual behavior ?

--Chunck Error Horse wont TP

Description of the actual behavior goes here.

--Tp Horse when chunk unloaded

--https://pastebin.com/K9iqj4SP

## Environment specifications

- Operating system : 

--Ubuntu Server 17

- Java version :

--Java 8

- Database : 

--MySQL

**Comment by Zedd7** [comment]
Hi, sorry for not having been available at the time. Please open this issue again if you are still encountering it.
