### ISSUE TITLE
How to set it up so opped players have more power?

### ISSUE THREAD

**Issue by catluvr9000** [Xibalba/ZHorse#72]
I am staff on a server focused around this plugin, and we have an issue where players leave their horses at spawn which causes lag and crashes. We were planning to keep the horses for three days, and if they are not taken by their owners until then we would auction them off to other players. But we can't use commands like /zh free, /zh claim, etc on other people's horses and can't find anything in the config files on making it so opped players can do so. Any advice?

**Comment by Zedd7** [comment]
Hello, what you are looking for is the [admin flag](https://github.com/Zedd7/ZHorse/wiki/Commands#advanced-use) : simply insert `-a` anywhere in a command and it will enable the admin mode if you have the required permission, thus override any protection.

I also suggest that you make use of the `/zh stable go` in addition with the config option Settings.use-default-stable: true) to send horses at the spawn to another location without putting them up for sale.
