### ISSUE TITLE
/zh claim won't work

### ISSUE THREAD

**Issue by thefallenone12** [Xibalba/ZHorse#74]
### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !
https://pastebin.com/93pvuLwC

## Question

Question goes here.
i can't use /zh claim on my server i keep getting an error

## Environment specifications

- Operating system : Windows

- Java version : 8

- Server version : 1.12.2

- ZHorse version : 1.6.8

- Database : SQLite

**Comment by Oruss7** [comment]
Hello, please add your permission plugin and if vault is installed too.

**Comment by Zedd7** [comment]
Hi, sorry for not having been available at the time. Please open this issue again if you are still encountering it.
