### ISSUE TITLE
Check Error Packet? 

### ISSUE THREAD

**Issue by ImdralRaenwood** [Xibalba/ZHorse#76]
I've got the plugin situated, mostly, but now it's giving me an entirely different issue. The SQL was working; I mean, at least the plugin now shows in-game menus and options. However, trying to operate a basic command such as /zh claim generates this mess:

20.11 02:21:44 [Server] INFO default: Joth_Horas_of_Styvurlie
20.11 02:21:41 [Server] WARN at java.lang.Thread.run(Unknown Source)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
20.11 02:21:41 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
20.11 02:21:41 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
20.11 02:21:41 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
20.11 02:21:41 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649)
20.11 02:21:41 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20.11 02:21:41 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.managers.CommandManager.onCommand(CommandManager.java:57)
20.11 02:21:41 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
20.11 02:21:41 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
20.11 02:21:41 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
20.11 02:21:41 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.commands.CommandClaim.<init>(CommandClaim.java:22)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.commands.CommandClaim.execute(CommandClaim.java:51)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.managers.DataManager.registerHorse(DataManager.java:452)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.database.SQLDatabaseConnector.executeUpdate(SQLDatabaseConnector.java:70)
20.11 02:21:41 [Server] WARN at com.github.xibalba.zhorse.database.SQLDatabaseConnector.executeUpdate(SQLDatabaseConnector.java:76)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
20.11 02:21:41 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
20.11 02:21:41 [Server] WARN com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'locationWorld' at row 1
20.11 02:20:34 [Server] INFO default: Joth_Horas_of_Styvurlie

Any thoughts on what this is?

**Comment by Zedd7** [comment]
Hi, sorry for not having been available at the time. Please open this issue again if you are still encountering it.
