### ISSUE TITLE
[Request] /zh here distance limiter

### ISSUE THREAD

**Issue by Rodzynus** [Xibalba/ZHorse#8]
Hello,
I'm using the plugin on a server that avoids abusive teleport mechanics, I kept /zh here command because horses tend to get stuck due to glitches or simply trapped on GriefPrevention protected regions and I need a way for players to retrieve their mounts.
Would it be possible to add distance limiter and/or cooldown on that command so people can't, for example, teleport multiple donkeys with chests across the map for easy item transport?

**Comment by Zedd7** [comment]
Hello, it's a good idea and I will implement it (cooldowns too but there were already planned).
However you might have to wait 2-3 months until I get some free time..

**Comment by Zedd7** [comment]
Hi, this feature might come sooner than expected (like tomorrow) because I have to make a release to fix /zh here incompatibility with 1.11 anyway ;)

**Comment by Rodzynus** [comment]
That's very good to hear, thanks for quick updates. ^_^
