### ISSUE TITLE
Zombie Horses can't be tamed unlike baby zombie horses

### ISSUE THREAD

**Issue by Sikatsu** [Xibalba/ZHorse#80]
## Feature request

Make it possible to tame adult undead horses.

**Comment by Zedd7** [comment]
Actually, not being able to tame an adult zombie horse is the default behaviour of Minecraft vanilla. So the bug report would rather be that it is possible to tame baby undead horses.

What I will do is add a config option `settings.allow-taming-of-undead-horse` that will block the taming of baby undead horses if set to `false` but allow the taming of both baby and adult undead horses if set to `true`.
