### ISSUE TITLE
[feature] admin can rename horse

### ISSUE THREAD

**Issue by Oruss7** [Xibalba/ZHorse#81]
Hello,

## Feature request

ZH Admins can't rename players's horses. Can you add this possibility please ?

- ZHorse version :
1.6.8

Thanks !

**Comment by Zedd7** [comment]
Hi, did you try to add the [admin flag](https://github.com/Zedd7/ZHorse/wiki/Commands#with-command-flags) anywhere in the command ?

Like this : `/zh rename HorseName -a`, when riding the horse.

**Comment by Oruss7** [comment]
no, i try

**Comment by Oruss7** [comment]
Working, ty
