### ISSUE TITLE
/zh here, /zh tp, etc all make horse invisible

### ISSUE THREAD

**Issue by ImdralRaenwood** [Xibalba/ZHorse#82]
So, when I use /zh here, or /zh tp, the horse I'm prompting disappears. I can't get it to reappear. 
It is saved in the database, and I can hear it near me, but it is invisible. 
I've tried switching the TP method to 'old' but that doesn't change anything. 
Running SpigotMC, 1.12.2

**Comment by Zedd7** [comment]
Are you sure that it occurs with `/zh tp` too ? This command only teleports the player.

**Comment by ImdralRaenwood** [comment]
I found that some combination of WorldGuard and Essentials/GroupManager was conflicting. 
I've managed to make it work, finally!
Thank you SO much.

Is there a way to *edit* a horse's statistics? Make it faster, slower, etc?

**Comment by Zedd7** [comment]
Nice ! Could you describe the steps (config lines) taken to fix that ?

It's not possible as of now (only with /zh spawn) but I was thinking of a /zh edit command
