### ISSUE TITLE
Q/A about this plugin

### ISSUE THREAD

**Issue by ProblemsSender** [Xibalba/ZHorse#83]
Is this plugin have or can you add an option to deny specific rank from right-click entity horse or open-chest-from-llama with specific permission just like LWC.deny from LWC plugin?
Or at least make they must claim the animal first to able to tame/add the chest/opening chest from it? # @

**Comment by Zedd7** [comment]
> Is this plugin have or can you add an option to deny specific rank from right-click entity horse or open-chest-from-llama with specific permission just like LWC.deny from LWC plugin?

Your question is not very clear so I'm not quite sure of what you mean.
But if the request is to prevent given groups from opening donkey/lama's chest, I won't do that for two reasons : 
1. The set of features and permission focused on horse's inventory management is already complex enough. Make sure to read the [wiki](https://github.com/Zedd7/ZHorse/wiki) so you have full understanding of how the plugin works.
2. An "opposite" permission already exists : `zh.lock.admin` allows players who own it to open the inventory of locked horses.

> Or at least make they must claim the animal first to able to tame/add the chest/opening chest from it?

ZHorse only deals with claimed horses. You should be looking for another plugin focused on inventory/chest management (such as LWC).
