### ISSUE TITLE
Horse duping and not going to stable on logout

### ISSUE THREAD

**Issue by dejakob1** [Xibalba/ZHorse#86]
### What are you trying to do ?
Testing out the new feature to send horse to stable on log out. 

### What is the expected behavior ?
Horse goes to stable when player logs out and horse gets tp'd when player uses /zhorse here

### What is the actual behavior ?
Horse doesn't go to stable when player logs out. Horse gets duplicated and duplicated horse get tp'd without saddle. Old horse stays. Neither of those horses go to stable on log out.

### How to reproduce the bug ?

/zhorse here
### Console output 

https://hastebin.com/wudayilise.md

Note: I added some lines from the new config to the old one. I didn't regenerated any other files.

## Environment specifications

- Operating system :  Windows

- Java version : 

- Server version : 1.12.1

- ZHorse version : 1.6.9

- Database :

**Comment by Zedd7** [comment]
Try updating to the very last build of Spigot 1.12.2
