### ISSUE TITLE
/zh list not working. Maybe somehow an SQL issue?

### ISSUE THREAD

**Issue by ImdralRaenwood** [Xibalba/ZHorse#88]
I am the same gent you spoke to on spigot. 
The zh here works, but the zh list does not. 

30.03 22:29:35 [Server] INFO Imdral_Raenwood issued server command: /zh list
30.03 22:29:35 [Server] WARN java.lang.reflect.InvocationTargetException
30.03 22:29:35 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
30.03 22:29:35 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
30.03 22:29:35 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
30.03 22:29:35 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.managers.CommandManager.onCommand(CommandManager.java:57)
30.03 22:29:35 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.03 22:29:35 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
30.03 22:29:35 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
30.03 22:29:35 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
30.03 22:29:35 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
30.03 22:29:35 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
30.03 22:29:35 [Server] WARN at java.lang.Thread.run(Unknown Source)
30.03 22:29:35 [Server] WARN Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
30.03 22:29:35 [Server] WARN at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
30.03 22:29:35 [Server] WARN at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726)
30.03 22:29:35 [Server] WARN at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.managers.PermissionManager.getPrimaryGroup(PermissionManager.java:26)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.managers.ConfigManager.getGroupName(ConfigManager.java:320)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.managers.ConfigManager.getClaimsLimit(ConfigManager.java:48)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.commands.AbstractCommand.getRemainingClaimsMessage(AbstractCommand.java:330)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.commands.CommandList.execute(CommandList.java:44)
30.03 22:29:35 [Server] WARN at com.github.xibalba.zhorse.commands.CommandList.<init>(CommandList.java:31)
30.03 22:29:35 [Server] WARN ... 21 more

**Comment by Zedd7** [comment]
Hi, could you follow the [template](https://github.com/Zedd7/ZHorse/blob/master/ISSUE_TEMPLATE.md) for the structure of tickets (including console logs in pastebin) ? It's easier to follow and reproduce like this.

**Comment by ImdralRaenwood** [comment]
Try this?

https://pastebin.com/5aQ2c0jC

**Comment by ImdralRaenwood** [comment]
Did the link work?

**Comment by Zedd7** [comment]
Yes but I still have no clue about the specs of your server as you did not follow the [template](https://github.com/Zedd7/ZHorse/blob/master/ISSUE_TEMPLATE.md) for tickets' structure.

What permission plugin are you using ?

**Comment by ImdralRaenwood** [comment]
Lol. 
https://pastebin.com/3CGsZ4Nv

GroupEssentials

**Comment by ImdralRaenwood** [comment]
I dunno half of this stuff, and most folks don't need to. Lol. 
I play on a Mac, but I have no idea how Beastnode chooses to host stuff. 
So... Windows? Linux? Dunno, don't supa care

**Comment by ImdralRaenwood** [comment]
And, here's the most recent permutation of this problem. 

This is NOT the full template, see two posts above for diagnostic information. This is a supplemental error log: 
https://pastebin.com/0pk157sE

**Comment by Zedd7** [comment]
Is this still an issue ?
It appears that I made no change at all in the code regarding groups or permissions in 1.6.9 and I could not find anything related to that in recent Spigot updates, however it does not mean that nothing has changed on that side.

In order to retrieve the permission group of players, ZHorse connects to Vault (which is a dependency plugin). The latter raised an error saying that your current permission plugin does not handle permission groups (which is currently mandatory to ZHorse). So it seems that either : 
1. This is indeed the case and I recommend you to try another permission plugin and see if it works.
2. Or you are using an newest version of Vault than 1.5.6, which I still need to investigate to see if it is compatible with ZHorse.
3. Or it is something else.

**Comment by ImdralRaenwood** [comment]
Sorry for my delay in getting back to you; 
It was some issue in setting up the MySQL/SQL Lite. 

Offhand, I don't recall what it was, other than that the .config formatting for the SQL section was rather redundant/out of order/confusing, and it took over a dozen adjusted variants/server restarts to finally get it "right."

But it's all working wonderfully. 

I wonder if there are other features you could add to the plugin. 
I know that you can use /zh here to summon them, but have you thought of incorporating a "Red Dead"-esque whistling system? Such that a character could type 

/me whistles unto Shadowfax

or some by-horse customizable text/command

and then the horse would actually *run* into view? Walk into character zone, as opposed to just appearing? 

* * * *

I'm not sure what else could be added. You could go for custom sounds/controls.
Perhaps creating a built-in family tree? I've had to do so manually, but I can track the horse lineages of the A'e Naehlian - A'i Nulia breeding. Their horse family line is now 6 generations. But, i have had to track it all myself. Having it track it all for you in some beautifully organized family tree file would be fucking bomb. 

I could keep spitballing, but I'll let up for now. ;)
