### ISSUE TITLE
World

### ISSUE THREAD

**Issue by DeluxeDom** [Xibalba/ZHorse#91]
### What are you trying to do ?
Enable the plugins on my world which use Multiverse.

I have gone into the config file and added the new worlds but now all that happens is when I type "/zh help" it comes up with "external error"
### What is the expected behavior ?
I would like to think that it adds the plugin on to the world allowing it to work.

Allowing the plugin to work on my pre-existing world.
### What is the actual behavior ?
It does not work.

It does not recognise my work and instead sends a message saying "external error".
### How to reproduce the bug ?

Went to my server panel, went to the config, Opened it up and added the worlds under the same format. Closed it and relaunched my server and it still did not work.

### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !
http://prntscr.com/k7ntir

## Question

Question goes here.
Is there anything in my coding that could be changed to make it work (link is above ^^).

## Environment specifications

- Operating system : 
Windows

- Java version :
9

- Server version :
1.12.2 (bukkit)

- ZHorse version :
1.6.9

- Database : 
SQlite

**Comment by Zedd7** [comment]
Could you add a pastebin.com link containing your server logs/console output? Ideally I need the output when you type /zh reload AND /zh help
