### ISSUE TITLE
/zh list doesnt work

### ISSUE THREAD

**Issue by ghost** [Xibalba/ZHorse#93]
### What are you trying to do ?

Description of the task to be done goes here. fix /zh list

### What is the expected behavior ? 

Description of the expected behavior goes here. it to open the list of horses

### What is the actual behavior ?

Description of the actual behavior goes here. it doesnt say anything at all

### How to reproduce the bug ?

1. Step 1 do /zh list
2. Step 2 no other step
3. ... i said no other step

### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !
i don't know how to do it 

## Environment specifications

- Operating system :

- Java version :

- Server version :

- ZHorse version :

- Database :

**Comment by Zedd7** [comment]
I will need more informations if you want help.
Start with filling the blanks for the server and zhorse version.
I will also need the server logs when you type `/zh list`. They are stored in the `logs` folder at the root of the server.
