### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by minecraft12321girl** [Xibalba/ZHorse#94]
ok so... im using the aternos server cuz im trying to make a horse server, im completely stuck on the commands!! it won't let me n my staff tame any horses! and ive gotten that permissionbukkit thing but i dont know how to use it ! :((( please help!! D: and how do i make it so members can do the /zh commands aswell? please help...! im terrible at coding :(( ive gone through https://github.com/Zedd7/ZHorse/wiki/Permissions and it still confuses me :((

**Comment by Zedd7** [comment]
Are you familiar with running a server at all ?

**Comment by minecraft12321girl** [comment]
i mean, this is my first one, my friend got the zh command to work but, we dont know how to make it so all players can use the commands

**Comment by Zedd7** [comment]
You must give them the permission `zh.use`

> You can give access to the basic set of commands and functionalities with the zh.use permission.

**Comment by minecraft12321girl** [comment]
how and where?

**Comment by Zedd7** [comment]
Sorry but your issue has nothing to do with ZHorse, you must learn how to set up a server in the first place.
Here is a tutorial to better understand the permissions system : https://bukkit.gamepedia.com/Understanding_Permissions
Then, I suggest that you check the tutorial of the permissions plugin that you are using.
For PermissionBukkit, just go to plugins/PermissionBukkit/config.yml and edit the file to your liking.
