### ISSUE TITLE
Stable/Spawn Mount

### ISSUE THREAD

**Issue by ABioGen** [Xibalba/ZHorse#97]
# Please be aware that ZHorse developement and maintenance is put on hold for the moment.
# However, this issue page remains open for questions and quick support.
# If your ticket requires modifications of the code, you will have to wait until either me or another developer resumes the project.

## Question

Hi,
 is there a way that i could set a global stable location ? every player have to set the stable location by themself.. and i try to spawn horse with 100% stats overall but idk how to :/
i tried this:

/zh spawn horse black tamed adult health 100% speed 100% jump 100%

obviously is this command wrong, can you tell me the right command please ?

## Environment specifications 

- Operating system : WIN 7 64bit

- Java version : 8

- Server version : 1.12.2

- ZHorse version : 1.7.0

- Database : No DB

**Comment by Zedd7** [comment]
Hi,

The global (default) stable location can be defined in the config by configuring the option `Settings.default-stable-location`.

Concerning the `/zh spawn` command, there is an entry for that command in the [Tips & tricks page](https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks) here : https://github.com/Zedd7/ZHorse/wiki/Tips-&-tricks#how-to-use-zh-spawn-

So, in this case, you want to do `/zh spawn horse black tamed adult health 30:100%:100%` (no 100% for the health as it only accepts integers).

**Comment by ABioGen** [comment]
awesome..nice thnx dude

**Comment by ABioGen** [comment]
hey....well call me an idiot^^ but /zh spawn horse black tamed adult health 30:100%:100% doesnt works here..i always got the message:

"Health is not a valid argument"
"the speed must be between 0.113 and 0.338"
"30:100%:100% is not a valid argument"
"incorrect number or type of arguments"

and every time i restart my server the spawned horses disapears. they are there but not shown...what can i do ?

**Comment by Zedd7** [comment]
My bad, `health` should not be in the command. I copied it from yours.
So in that case the correct one is `/zh spawn horse black tamed adult health 30:100%:100%`

However, the message "the speed must be between 0.113 and 0.338" shows that you are using the exact stats display mode, meaning that stats are real values and not percentages.
So either switch to the other stat display mode with `/zh settings settings stats <mode>` or use zh spawn with real values (without %), like `/zh spawn horse black tamed adult health 30:0.2:`.

**Comment by ABioGen** [comment]
/zh spawn horse black tamed adult 30:100%:100% works now in Display Mode rounded and i solved the other problem^^..thank you so much for the help dude..xD

**Comment by Zedd7** [comment]
You're welcome. If you want some real fun try `/zh spawn horse black tamed adult 30:500%:500% -a`

**Comment by ABioGen** [comment]
hahahhaha wtf^^...niiice^^..but really fast^^ cant handle it^^... ok well i still have a problem if i restart my server, then the mounts disappear (kinda hiding or something like that), if i use /zh here my mount appears again. can u tell me what the problem is ? btw u said english isnt your native language. can you talk in german maybe ? and i have a suggestion: it would be very cool if we could tame and ride spiders, enderdrages, turtles ect. would this possible in the future ?

**Comment by Zedd7** [comment]
Check that your default location is not in a protected area (by another plugin). When you restart your server  all horses go to their stable, that might be that.

About your suggestion : the development of ZHorse is halted so it would have to come from another developer who wishes to take over ZHorse.
