### ISSUE TITLE
ZHorse Console Error

### ISSUE THREAD

**Issue by BakProject** [Xibalba/ZHorse#98]
# Please be aware that ZHorse developement and maintenance is put on hold for the moment.
# However, this issue page remains open for questions and quick support.
# If your ticket requires modifications of the code, you will have to wait until either me or another developer resumes the project.

### What are you trying to do ?

Clear Console Errors

### What is the actual behavior ?

Gives a Null Error in console

### How to reproduce the bug ?
It just happens in console. No reason?

### Console output 

Link to console output, if any, goes here. Please use http://pastebin.com to paste long outputs !
https://pastebin.com/V4W0xykm

## Environment specifications

- Operating system :
Windows

- Java version :
8

- Server version :
1.12.2

- ZHorse version :
1.7.0

- Database :

**Comment by Zedd7** [comment]
Hi,

The error message you see is shown every time the server unloads a chunk in which a claimed horse is standing. It indicates that it could not update the horse's statistics, inventory and location in the database. This is not critical but could cause some problem is the horse is killed/lost or if a player wants to teleport it.

The thing is that ZHorse tries to use a [Spigot's method](https://github.com/Zedd7/ZHorse/blob/master/src/main/java/com/github/zedd7/zhorse/database/HorseInventoryRecord.java#L36) which is reported non-existent by Spigot, although it does exist : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/AbstractHorse.html#getInventory--

I tested it myself (just letting a chunk unload with a claimed horse on it does the trick) and could not reproduce your issue, neither with a very old Spigot 1.12.2 jar nor with the very last one.

So, I suggest that you update everything (Spigot 1.12.2, Java 8) and see if it helps. If not, I'm afraid that I don't have time for extensive tests. :/
